/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Componentes;

import ClasesLogica.Superviviente;
import ClasesLogica.Zombie;
import ClasesLogica.MansiónZombie;
import Botones.BotonXCierre;
import Botones.BotonInicio;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JLabel;

/**
 *
 * @author guillermo.camher
 */
public class Inicio extends javax.swing.JFrame implements ActionListener {

    //Declaración de variables
    private final SelectorDificultad selectorDificultad;
    private Font fuenteEstandar;
    static Color colorFuente = new Color(233, 216, 197);
    static BotonInicio botonInicio = new BotonInicio();
    
    //Objetos superviviente y zombie
    static Superviviente superviviente;
    static Zombie zombie;

    //Funciones
    private void crearDialogoAcciones() {
        Acciones dialogoAcciones = new Acciones(null, true);
        dialogoAcciones.setVisible(true);
    }

    private enum enumDificultades {
        Fácil, Medio, Difícil
    }; //Se crea un enumerado que contiene las diferentes opciones de dificultad, con la finalidad de evitar errores sintácticos.

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        try {
            this.fuenteEstandar = Font.createFont(Font.TRUETYPE_FONT, new File("src/fuentes/GhoulFriAOE.ttf")).deriveFont(30f);//Se inicializa la fuente a utilizar 
        } catch (FontFormatException ex) {
            System.out.println("Error en el formato de la fuente: " + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Error entrada salida: " + ex.getMessage());
        }
        this.setUndecorated(true);

        initComponents();
        this.setSize(1920, 1080);//Definicion del tamaño de la ventana
        this.setLocationRelativeTo(null);//Se establece la posición en el centro de la pantalla

        //Fondo de la ventana, panel con imagen dibujada.
        FondoVentanaInicio panelFondo = new FondoVentanaInicio();
        panelFondo.setSize(1920, 1080);
        panelFondo.setVisible(true);
        this.setContentPane(panelFondo);

        //Boton encargado del cierre de la ventana
        BotonXCierre botonCierre = new BotonXCierre();
        this.add(botonCierre);
        botonCierre.setLocation(0, 0);
        botonCierre.setSize(35, 35);
        botonCierre.setBackground(new Color(204, 172, 92));
        botonCierre.setFocusable(false);
        botonCierre.addActionListener(this); //Se añade action listener que recurre al metodo ActionPerformed de la ventana principal

        //Selector de dificultad
        selectorDificultad = new SelectorDificultad();
        this.add(selectorDificultad);
        selectorDificultad.setFont(fuenteEstandar);
        selectorDificultad.setBackground(new Color(56, 33, 14));
        selectorDificultad.setBounds(850,700,230,70);
        selectorDificultad.addItem(enumDificultades.Fácil);
        selectorDificultad.addItem(enumDificultades.Medio);
        selectorDificultad.addItem(enumDificultades.Difícil);

        //Boton para iniciar el juego
        this.add(botonInicio);
        botonInicio.setBounds(1150,675,270,120);
        botonInicio.addActionListener(this);

        //Texto para seleccion dificultad
        JLabel textoDificultad = new JLabel("Elija la dificultad:");
        this.add(textoDificultad);
        textoDificultad.setFont(fuenteEstandar);
        textoDificultad.setForeground(colorFuente);
        textoDificultad.setBounds(600, 700, 350, 70);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object componenteProcedencia = e.getSource();

        //Cerrado de la ventana principal
        if (componenteProcedencia.getClass() == BotonXCierre.class) { //Se comprueba si el componente que ha invocado el action performed es el boton de salida de pantalla
            System.exit(0);
        }

        if (componenteProcedencia.getClass() == BotonInicio.class) { //Se comprueba que el componente que ha invocado el action listener es el boton de inicio y se ejecutan las acciones correspondientes
            //Seleccion de dificultad
            String opcionDificultad = selectorDificultad.getSelectedItem().toString(); //Se extrae el valor elegido con el selector de dificultad
            System.out.println(opcionDificultad);

            if (opcionDificultad == enumDificultades.Fácil.toString()) {
                ClasesLogica.MansiónZombie.cantidadHabitaciones = 5;
                System.out.println("Se ha elegido el nivel facil, hay " + ClasesLogica.MansiónZombie.cantidadHabitaciones + " habitaciones");
            }
            if (opcionDificultad == enumDificultades.Medio.toString()) {
                ClasesLogica.MansiónZombie.cantidadHabitaciones = 7;
                System.out.println("Se ha elegido el nivel medio, hay " + ClasesLogica.MansiónZombie.cantidadHabitaciones + " habitaciones");
            }
            if (opcionDificultad == enumDificultades.Difícil.toString()) {
                ClasesLogica.MansiónZombie.cantidadHabitaciones = 10;
                System.out.println("Se ha elegido el nivel dificil, hay " + ClasesLogica.MansiónZombie.cantidadHabitaciones + " habitaciones");
            }

            //Inicializacion de los atributos
            MansiónZombie.intentosBusqueda = 3;
            MansiónZombie.habitacionActual = 1;
            MansiónZombie.numeroZombiesXHabitacion = 1;
            System.out.println("Atributos inicializados");
            superviviente = new Superviviente();
            zombie = new Zombie();

            //Se abre el dialogo en el que se encuentran todas las acciones disponibles.
            this.crearDialogoAcciones();
        }
    }
}
